#!/bin/bash
	
function dep_test {
	which $1 2>&1 | rg -o 'which: no' | xargs -i echo 0
}

function test_all {
	cmds=("libinput" "rg" "fd" "unbuffer" "xargs" "showkey")
	for cmd in "${cmds[@]}"
	do
		res=`dep_test $cmd`
		if [ "$res" == "0" ]
		then
			echo $cmd is not installed
			exit 1
		fi
	done
}

function check_rg {
	ver=`rg --version | rg 10 | xargs -i echo 1`
	if [ "$ver" != "1" ]
	then
		echo minimum rg version needed is 0.10.0
		exit 1
	fi
}

# Check dep
test_all
check_rg

# Run
device=`sudo libinput list-devices | rg -A 1 'USB USB Keyboard$' | rg -o 'event[0-9]*'`

if [ -z $device ]
then
	echo Plug in keyboard then try again
	exit 1
fi

input=`fd $device /sys/devices  | rg -o 'input[0-9]+'`

current_state=`cat /sys/class/leds/$input::scrolllock/brightness`
modifier="$((! current_state))"

echo All set.

while true
do

sudo unbuffer showkey | rg --line-buffered '70 press' |
 xargs -i echo $modifier | sudo tee /sys/class/leds/$input::scrolllock/brightness |
 xargs -i sudo pkill showkey

modifier="$((! modifier))"
done
