#!/bin/bash
	
COMMANDS=(
  	libinput
  	rg
  	fd
	xargs
	showkey
	)
	
function checkCommands() {    

    if [[ $(which --help 2>/dev/null) ]] && [[ $(echo --help 2>/dev/null) ]]; then

        local a=0
        for command in ${@}; do
            if [[ ! $(which $command 2>/dev/null) ]]; then
                COMMANDS_NOTFOUND[$a]=$command
                let a++
            fi
        done

        if [[ -n $COMMANDS_NOTFOUND ]]; then
            echo -e "\nError! The following commands could not be found: ${COMMANDS_NOTFOUND[*]}\nAborting\n"
            exit 1
        fi
    else
        exit 1
    fi
}

# Check dep
checkCommands "${COMMANDS[*]}"
check_rg

# Run
device=`sudo libinput list-devices | rg -A 1 'USB USB Keyboard$' | rg -o 'event[0-9]*'`

if [ -z $device ]
then
	echo Plug in keyboard then try again
	exit 1
fi

input=`fd $device /sys/devices  | rg -o 'input[0-9]+'`

current_state=`cat /sys/class/leds/$input::scrolllock/brightness`
modifier="$((! current_state))"

echo All set.

while true
do

sudo unbuffer showkey | rg --line-buffered '70 press' |
 xargs -i echo $modifier | sudo tee /sys/class/leds/$input::scrolllock/brightness |
 xargs -i sudo pkill showkey

modifier="$((! modifier))"
done
